name: ci lint and build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_job:
    name: lint and build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm i

      - name: esLint
        run: npm run lint:es

      - name: styleLint
        run: npm run lint:scss

      - name: build
        run: npm run build
